### ISSUE TITLE
Unable to run SwiftShield with Jenkins-Fast lane for iOS project.

### ISSUE THREAD

**Issue by amolpict** [rockbruno/swiftshield#102]
Hi @rockbruno,
I am able to run the command separately on project and swifshield able to obfuscate code as well.
I was trying to run it through Jenkins job with fastlane but its seems no plugin is there for SWIFT-SHIELD. Is it correct ? 
If plugin is not there,  Is it some thing we need to use in builds scripts of the code or it can be done on CI with script ?

Thanks,
Amol

**Comment by rockbruno** [comment]
Hey! You can run bash commands in fastlane. I think it's`sh("the command")`.

**Comment by amolpict** [comment]
Thanks for Quick reply. Let us try at our end .
