### ISSUE TITLE
reuseIdentifier not obfuscated

### ISSUE THREAD

**Issue by jorgepalacioGL** [rockbruno/swiftshield#104]
is there a way to obfuscate the reuse identifier value in the xml document?
Tried doing the following but didn't work
```
if let customClass = element.attributes["reuseIdentifier"], let protectedClass = obfuscationData.obfuscationDict[customClass] {
            Logger.log(.protectedReference(originalName: customClass, protectedName: protectedClass))
            element.attributes["reuseIdentifier"] = protectedClass
        }
````
I see at the end the protector iterates on each children of the element with
`for child in element.children {`
but still the `reuseIdentifier` value is not updated
any thoughts?

**Comment by rockbruno** [comment]
I think you need to be more careful with that as you might be obfuscating something that belongs to a class that shouldn't be obfuscated (I believe the obfuscation of the main class of the xib does this check), but this code looks correct. Have you debugged it to see where it fails?

**Comment by jorgepalacioGL** [comment]
I just debugged and find out the issue, actually the cell identifiers were not equal to the custom class, so the condition was not met.

Will close this, thanks!
