### ISSUE TITLE
Identifier Name Violation : Function name should start with Lower Case

### ISSUE THREAD

**Issue by amolpict** [rockbruno/swiftshield#106]
After obfuscation on project I am getting "**Identifier Name Violation : Function name should start with Lower Case**" in almost every file. Function names are replaced with value starting with Uppercase.
Any thoughts on this, how to fix ?

**Comment by rockbruno** [comment]
I assume you're talking about SwiftLint? In this case, see: https://github.com/rockbruno/swiftshield#modify-scripts-that-can-affect-swiftshield

**Comment by rockbruno** [comment]
Closing because this is unrelated to SwiftShield.

**Comment by amolpict** [comment]
Yeah I agree. 
But when I obfuscate code, some function names gets obfuscated. Some with initial letter lowerCase and some function names with Uppercase Initial letter.
E.g 
func yhdnBndhhsgTmngdsdsdg() { } // This one works
func **ThdhgjandmdnajdDmSesa**() { } // **This one throws error Function name should start with lower. Its in thousand files actually.**

**Comment by rockbruno** [comment]
Please see https://github.com/rockbruno/swiftshield#modify-scripts-that-can-affect-swiftshield, it shows how to prevent this issue. Basically, you shouldn't run swiftlint after obfuscating the code.

**Comment by amolpict** [comment]
> Please see https://github.com/rockbruno/swiftshield#modify-scripts-that-can-affect-swiftshield, it shows how to prevent this issue. Basically, you shouldn't run swiftlint after obfuscating the code.

Ok @rockbruno.  Let me check this one. Thanks :)
