### ISSUE TITLE
Obfuscated code for class not shown/indexed, when used with "is" operator

### ISSUE THREAD

**Issue by amolpict** [rockbruno/swiftshield#107]
In project I have something like this :
 if let navigationController = viewController as? UINavigationController,
            navigationController.viewControllers.first is **TestViewController**
 {
            button.isHidden = true
} 
When I run command, it obfuscate "TestViewController".
But when I use it with "is" operator it does show TestViewController and not obfuscate code

Generally it should be : 

if let navigationController = viewController as? UINavigationController,
            navigationController.viewControllers.first is **bfdhTjdnjahdaTjakdjjdaT** 
{
            button.isHidden = true
 } 

Any one know why it's not happening or its not supported here ?
Any workaround ?

**Comment by rockbruno** [comment]
This issue has been fixed recently in Swift, it should stop happening in the next Xcode release. Until then you have to stop doing it or fix it manually unfortunately.

**Comment by amolpict** [comment]
@rockbruno Thanks for the information. Wondering now how/what to replace it with. Something like manual check similar to "is" type check operator in swift.

**Comment by rockbruno** [comment]
I think you can use the `as` operator to fix it. I believe that one works.
`if case _ = nav.first as Type`

**Comment by amolpict** [comment]
Thanks @rockbruno for suggestion. Closing hence we not going with alternatives.
