### ISSUE TITLE
ignore-modules not working

### ISSUE THREAD

**Issue by snehageorge** [rockbruno/swiftshield#118]
**XCode** - 11.3.1
**Language** - Swift

I tried to obfuscate my project using the following command in terminal
`swiftshield obfuscate --project-file /Users/me/Desktop/\ Projects/myProject-ios/myProject/myProject.xcworkspace --scheme myProject-Staging --ignore-public --verbose --dry-run --print-sourcekit`
But I got errors 
`Error: Error Domain=com.rockbruno.swiftshield Code=0 "error response (Request Failed)`
These errors are in various files in my Pods folder. I am using Pods in my project. **I want to exclude these pod libraries from being obfuscated.**

I tried the following commands:
`swiftshield obfuscate --project-file /Users/me/Desktop/\ Projects/myProject-ios/myProject/myProject.xcworkspace --scheme myProject-Staging --ignore-public -ignore-modules<Lottie> --verbose --dry-run --print-sourcekit`
and
``swiftshield obfuscate --project-file /Users/me/Desktop/\ Projects/myProject-ios/myProject/myProject.xcworkspace --scheme myProject-Staging --ignore-public -ignore-modules<Lottie, ObjectMapper> --verbose --dry-run --print-sourcekit``
But I am getting errors :
`zsh: no such file or directory: Lottie`
`zsh: no such file or directory: ObjectMapper`

I am facing errors in ObjectMapper and lottie-ios.
I tried with name in podfile(lottie-ios), and import name(Lottie), but still facing the same errors.

**How can I fix this?**

**Comment by rockbruno** [comment]
This is the correct way of using it:
`-ignore-modules Lottie,ObjectMapper`

**Comment by rockbruno** [comment]
As a tip, you should always be using the latest Xcode version when using this tool. The list of limitations is guaranteed for the latest version only.

**Comment by snehageorge** [comment]
> This is the correct way of using it:
> `-ignore-modules Lottie,ObjectMapper`

I tried 
`swiftshield obfuscate --project-file /Users/me/Desktop/\ Projects/myProject-ios/myProject/myProject.xcworkspace --scheme myProject-Staging --ignore-public -ignore-modules Lottie,ObjectMapper --verbose --dry-run --print-sourcekit`
but got error 
**Error: Missing value for '-s <scheme>'**
I changed the scheme, thinking the - in the scheme name might be a problem, and tried:
`swiftshield obfuscate --project-file /Users/me/Desktop/\ Projects/myProject-ios/myProject/myProject.xcworkspace --scheme myProject --ignore-public -ignore-modules Lottie,ObjectMapper --verbose --dry-run --print-sourcekit`
**Getting same error**

**Comment by rockbruno** [comment]
It's a double dash `--ignore-modules`, not one.

**Comment by snehageorge** [comment]
> It's a double dash `--ignore-modules`, not one.

I tried that also:
`swiftshield obfuscate --project-file /Users/me/Desktop/\ Projects/myProject-ios/myProject/myProject.xcworkspace --scheme myProject --ignore-public --ignore-modules Lottie,ObjectMapper --verbose --dry-run --print-sourcekit`
Getting error
`Error: Unexpected argument 'Lottie,ObjectMapper'`

**Comment by rockbruno** [comment]
Ahh I see it now. The name of the argument is `--ignore-targets`, it's the documentation that is wrong. You can see it in the help window. I'll fix the docs

**Comment by snehageorge** [comment]
> Ahh I see it now. The name of the argument is `--ignore-targets`, it's the documentation that is wrong. You can see it in the help window. I'll fix the docs

That fixed those errors.

But now I am getting the following error:
`Error: Error Domain=com.rockbruno.swiftshield Code=0 "error response (Request Failed): error opening input file '/Users/me/Desktop/iOs\ Projects/myProject-ios/myProject/AppDelegate.swift' 
(No such file or directory)" UserInfo={NSLocalizedDescription=error response (Request Failed): error opening input file '/Users/me/Desktop/iOs\ Projects/myProject-ios/myProject/AppDelegate.swift' (No such file or directory)}`

**Comment by rockbruno** [comment]
I don't think SourceKit supports spaces in folders. This is a bug https://github.com/rockbruno/swiftshield/issues/108

**Comment by snehageorge** [comment]
> I don't think SourceKit supports spaces in folders. This is a bug #108

Ok, thanks, removed the spaces in folders, and it worked. 

Now obfuscating is shown as success, but there is no conversionMap.txt file in swiftshield-output folder. 
```
--- Tagging projects
--- Preparing conversion map
```

How can I verify if the obfuscation is a success or failure?

**Comment by rockbruno** [comment]
Your input above shows you're using `--dry-run`, which avoids saving files. Make sure you're using the correct args

**Comment by snehageorge** [comment]
> Your input above shows you're using `--dry-run`, which avoids saving files. Make sure you're using the correct args for your case

Thank you so much. It works now.

**Comment by CanfieldMobileDev** [comment]
Hello,
I am confused by the change from --ignore-modules to --ignore-targets. Are we talking about actual Xcode project targets? While I do need to ignore "modules" that are defined by dependent frameworks in my project, these "modules" are not built by "targets". What should I do now?

**Comment by rockbruno** [comment]
It only works for actual modules. The naming wasn't a good idea in hindsight.

**Comment by CanfieldMobileDev** [comment]
Got it! Thanks.
