### ISSUE TITLE
Build error: missing Csourcekitd_Info.plist

### ISSUE THREAD

**Issue by CanfieldMobileDev** [rockbruno/swiftshield#120]
I am getting this error in both v4.0.3 and v4.1.0. Also I can't find the file in the project tree.

error: Build input file cannot be found: '<my dir>'/swiftshield.xcodeproj/Csourcekitd_Info.plist' (in target 'Csourcekitd' from project 'swiftshield')

Thank you.

**Comment by rockbruno** [comment]
Hey, the project being committed is a mistake. This is a SwiftPM project so you need to build it with `swift package generate-xcodeproj`

**Comment by rockbruno** [comment]
I've deleted the files from the repo. Thanks for the warning!

**Comment by CanfieldMobileDev** [comment]
Thank you for addressing quickly
