### ISSUE TITLE
Getting Segmentation fault: 11

### ISSUE THREAD

**Issue by Kruks** [rockbruno/swiftshield#20]
I'm trying to do manual Obfuscation, the files in my project gets obfuscated as expected, but it gives error "Segmentation fault: 11" when trying to read pod files as a result the pod files don't get obfuscated.

**Comment by rockbruno** [comment]
Hi @Kruks , are your pod files unlocked? CocoaPods locks it's folder by default, so you need to unlock them for this tool to work. You can see an example at [USAGE.md](https://github.com/rockbruno/swiftshield/blob/master/USAGE.md)
