### ISSUE TITLE
AWS Module Can't Detect

### ISSUE THREAD

**Issue by MagicalWater** [rockbruno/swiftshield#40]
AWS is a Obj-C module
```
  pod 'AWSCore', '~> 2.6.31'
  pod 'AWSSNS', '~> 2.6.31'
  pod 'AWSCognito', '~> 2.6.31'
```

i added it to -ignore-modules 
but it's not work, and last used -verbose
it not found all the aws module

**Comment by rockbruno** [comment]
I don't understand what you were expecting to happen, can you clarify your issue a bit? This tool only works with Swift modules by the way.

**Comment by MagicalWater** [comment]
This is my shell

```
PROJECT_PATH=/Users/magicalwater/iOSProjects/RxTest
PROJECT_FILE=RxTest.xcworkspace
IGNORE_LIB=AWSCore
TARGET=RxTest
chmod -R 774 "${PROJECT_PATH}"
"${SCRIPT_PATH}"/swiftshield -property-include -automatic -project-root "${PROJECT_PATH}" -automatic-project-file "${PROJECT_PATH}/${PROJECT_FILE}" -ignore-modules "${IGNORE_LIB}" -automatic-project-scheme "${TARGET}"
```

I want ignore AWSCore, but AWSCore still obfuscated.

AWSCore is a Obj-C Framework, it can't used auto mode?

**Comment by hadiidbouk** [comment]
I am using this library with ArcGIS framework, which is an obj-c framework, and it works fine with me

**Comment by rockbruno** [comment]
Hahaha that's great news! I would be in trouble if this tool somehow leaked in obj-c 😛 
Will be closing this one, feel free to open more issues if a different one is found.
