### ISSUE TITLE
Incorrect mapping for singleton

### ISSUE THREAD

**Issue by LikimsJaromirB** [rockbruno/swiftshield#42]
Having  the following code with tag  __s (custom tags have the same issue):
ClassName__s.shared__s.methodName__s
swiftshield is mapping whole chain of calls in a strange way, ignoring dots and not converting whole part of a class name etc. 
AccidentManager__s.shared__s.crashDetector__s  method call was converted to AcciTPaRNEntdrLwWFCPBMwsOnZCzusaJTuErMvvdDtyOVZOJBFrxLGnZolnuadyVnUiRsasjMvRCBFmSZBnAQPmVsZICejHmsODKh, where conversionMap.txt contains following mapping:
AccidentManager__s ===> ZJXprYewPqDipmLlEKGSgPsTszDqEcvt
shared__s ===> QcakTJnwEMiWGLgjzFbRWOTQOGZuWsXg
crashDetector__s ===> ZkbUQUYlQXHiLVnUEsmFrLHqEHyLigpX
ed__s.cra ===> MvvdDtyOVZOJBFrxLGnZolnuadyVnUiR
dentManager__s.sha ===> TPaRNEntdrLwWFCPBMwsOnZCzusaJTuE
hDetector__s ===> asjMvRCBFmSZBnAQPmVsZICejHmsODKh

This results in a compiler error.

**Comment by rockbruno** [comment]
Since it ignored part of the word it looks like something threw the indexes off, are there emojis in the file somewhere? If you could share the full file where that happened I could investigate better.

**Comment by LikimsJaromirB** [comment]
@rockbruno unfortunately I can’t because it’s a commercial project. Yes there are some emojis for the log purposes in the same file where the crashDetector__s method is called but these emojis are used in other function and it looks like below:
**Log.trace("💎 Beacon FAR     🍄")** 

In the AccidentManager__s class there are no emojis used.

**Comment by rockbruno** [comment]
No problem! The emojis screw up obfuscating for the entire file because SourceKit treats each code point as one character, while the string iterators treat the emojis itself as a single character. I might be able to fix that in Swift 5, but for now I would try removing them and see if that fixes the problem 😢

**Comment by LikimsJaromirB** [comment]
Ok, thanks a lot ! :)

**Comment by LikimsJaromirB** [comment]
@rockbruno  are the commented lines of code indexed as well ? Because only when I remove code with emojis the library seems to obfuscate code properly.

**Comment by rockbruno** [comment]
They're not indexed themselves, but since SourceKit shows the exact location of type references, the commented lines will still affect indexing.

**Comment by LikimsJaromirB** [comment]
That explains everything, thanks 😀
