### ISSUE TITLE
Hey, If i change "swiftshield-Sources", How do I build a new bin to test my changes?

### ISSUE THREAD

**Issue by YunyueLin** [rockbruno/swiftshield#58]
![How to create this file?](https://user-images.githubusercontent.com/12877953/58700543-e7646d00-83d2-11e9-9f36-c1e9c12b179d.png)
I want to change the func(random(length: Int, excluding: Set<String>))

**Comment by rockbruno** [comment]
Hey there, the way I publish this is by archiving (Product -> Archive) in Xcode. You can get a binary this way :)

**Comment by YunyueLin** [comment]
That works! Thanks :)
