### ISSUE TITLE
Config file is unavailable in master.

### ISSUE THREAD

**Issue by ThirumalSiva** [rockbruno/swiftshield#60]
Created new project(SwiftShieldSample) and added "swiftshield" using "cocoapods".
Open terminal cd /Users/*****/Desktop/Sample/SwiftShieldSample.
./swiftshield -automatic -project-root ./ -automatic-project-scheme SwiftShieldSample -automatic-project-file ./SwiftShieldSample.xcworkspace.
-bash: ./swiftshield: No such file or directory.

<img width="570" alt="Screenshot 2019-06-04 at 11 25 14 AM" src="https://user-images.githubusercontent.com/13433105/58854610-71eeea00-86bb-11e9-8a48-1d62eaac0407.png">

Do I miss anything.

**Comment by ThirumalSiva** [comment]
<img width="283" alt="Screenshot 2019-06-04 at 2 04 57 PM" src="https://user-images.githubusercontent.com/13433105/58864096-c604c900-86d1-11e9-8164-bc4c33ce5fd3.png">

Getting below error:

ios_hypto thirumals$ /Users/thirumals/Desktop/ios_hypto/Pods/SwiftShield/swiftshield -automatic -project-root /app/Hypto -automatic-project-file /app/Hypto.xcworkspace -automatic-project-scheme Hypto -show-sourcekit-queries
SwiftShield 3.3.1
Automatic mode
Building project to gather modules and compiler arguments...
-- Searching for references of the retrieved USRs --
Found nothing to obfuscate. Finishing...

**Comment by rockbruno** [comment]
The version in CocoaPods is very old and not supported. You should use the one from the releases tab.
Try updating it, the version you're using doesn't print xcodebuild errors which should show you the real problem.

**Comment by ThirumalSiva** [comment]
Thanks for the update.
