### ISSUE TITLE
Method name obfuscation

### ISSUE THREAD

**Issue by rockbruno** [rockbruno/swiftshield#7]
Easy, but how do I deal with standard lib methods like tableView_didSelect(row:at:) ? A massive dictionary of forbidden words like classes? Perhaps I can run the app and extract the method names via the OBJ-C runtime...

**Comment by cunzhegao** [comment]
does the latest release support methods obfuscation?

**Comment by rockbruno** [comment]
Hmm, after printing SwiftShield logs, it looks like they do indicate that it's related to UIKit now:

```
          key.kind: source.lang.swift.decl.function.method.instance,
          key.name: "tableView(_:didSelectRowAt:)",
          key.usr: "c:@M@test@objc(cs)ViewController(im)tableView:didSelectRowAtIndexPath:",
          key.line: 12,
          key.column: 10,
          key.is_dynamic: 1,
          key.related: [
            {
              key.kind: source.lang.swift.ref.function.method.instance,
              key.name: "tableView(_:didSelectRowAt:)",
              key.usr: "c:objc(pl)UITableViewDelegate(im)tableView:didSelectRowAtIndexPath:"
            }
          ],
```

I think it's now possible.

**Comment by rockbruno** [comment]
@cunzhegao `3.2.0` obfuscates the method's main names.
Arguments are still not obfuscated, but I'll add support for them soon.

**Comment by rockbruno** [comment]
I'll close this since the feature is supported, but feel free to tag me!

**Comment by cunzhegao** [comment]
ok, i'll take a look, thank you!

**Comment by cunzhegao** [comment]
hey bruno, how can i avoid obfuscating public class and method？

**Comment by rockbruno** [comment]
Hi @cunzhegao , the current version has no way to avoid that but it's very possible to implement, are you trying to pre-obfuscate a library or something like that?
