### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by gauravborole** [rockbruno/swiftshield#71]
To run it, I am using below SwiftShield tool in terminal:

swiftshield -automatic -project-root /app/MyApp -automatic-project-file 
/app/MyApp/MyApp.xcworkspace -automatic-project-scheme MyApp-AppStore
Getting error:

dyld: Library not loaded: @rpath/sourcekitd.framework/Versions/A/sourcekitd
Referenced from: /usr/local/bin/swiftshield
Reason: image not found
Abort trap: 6

I am using macOS 10.14.6.

What could be the issue? How to install SwiftShield

**Comment by rockbruno** [comment]
Do you have Xcode command line tools installed? This could also happen if your Xcode is on a different folder than `/Applications` (as this search path is hardcoded into the project)

**Comment by gauravborole** [comment]
Thanks rockbruno

I had 2 Xcode versions were installed on my machine 
/Applications/Xcode10.3.1.app
/Applications/Xcode11.1.app

I have deleted **_Xcode10.3.1.app_** and renamed **_Xcode11.1.app_** to **_Xcode.app_**. Issue got resolved now.

**Comment by AleksanderDeveloper** [comment]
guroba@MacBook-Pro-Aleksandr Desktop % sudo chmod 755 swiftshield
guroba@MacBook-Pro-Aleksandr Desktop % sudo cp -r swiftshield /usr/local/bin/zsh 
guroba@MacBook-Pro-Aleksandr Desktop % swiftshield --help
zsh: permission denied: swiftshield

**Comment by AleksanderDeveloper** [comment]
What should I do see such a mistake?
