### ISSUE TITLE
Obfuscation hash is being shifted

### ISSUE THREAD

**Issue by jotahws** [rockbruno/swiftshield#89]
- Type: BUG
- Swift v4.2
- Swiftshield v3.5.0

I'm having trouble obfuscating a particular file. It seems that the hash generated by the Obfuscator is shifting the first two characters, causing it to mess up the rest of the code:

Command: `swiftshield -manual -project-root Users/Me/MyProject/ -tag __z`

<img width="427" alt="Captura de ecrã 2020-01-23, às 10 25 09" src="https://user-images.githubusercontent.com/19479028/72976512-a4746100-3dca-11ea-970f-7f20e30ce1a5.png">

I don't know what this is caused by, but I guess there's anything in the first obfuscated variables that is affecting the rest of the refactoring process

Is this a known bug? And is there any workaround for that?

**Comment by rockbruno** [comment]
Weird question, but are there emojis somewhere in the file? They are an example of characters that can cause this bug because of how Unicode works

**Comment by jotahws** [comment]
No, but there are "Ç"s and "Ã"s.

**Comment by rockbruno** [comment]
I think that causes it then. Can you check if removing them fixes the issue?

**Comment by jotahws** [comment]
Yes that works. After I removed every latin character it ran normally. Does that mean this tool only supports 1-byte characters?

**Comment by jotahws** [comment]
If anyone is having the same problem, I suggest changing the special characters to its unicode value

https://docs.swift.org/swift-book/LanguageGuide/StringsAndCharacters.html#ID295
