### ISSUE TITLE
"swiftshield: command not found" during Automatic mode in Mac-terminal

### ISSUE THREAD

**Issue by amolpict** [rockbruno/swiftshield#95]
Hi Team,

I installed SwiftShield through cocoa pods in Xcode project and trying to run swiftshield through Mac-terminal for Automatic mode but I am getting "swiftshield: command not found" error and unable to run swift shield. Am I missing anything here. Is there any prerequisite needs to be done to run swift shield successfully ?
Please suggest.

Thanks,
Amol.

**Comment by rockbruno** [comment]
If you installed through Cocoapods then you need to reference the binary from inside the Pods folder

I don't support cocoapods anymore though, the latest version is only available from the releases part of the repo 👍

**Comment by amolpict** [comment]
@rockbruno Thanks for confirming. So we don't need any setup in iOS mobile app for "SwiftShield". 
We can just have this binary on CI server, Point to release branch and run the command for Project. Is this understanding correct ?
Also, do we need scripting on CI server to execute this ? Can you please provide some details on this, that would be helpful ?
Thanks :)

**Comment by rockbruno** [comment]
I recommend shipping the binary with the repo so it's easier to control its versions. Besides that, you don't need any custom script for the CI, just run it as you would locally.

**Comment by amolpict** [comment]
Thanks @rockbruno . On Mobile app side we don't need pod installation anymore. We have to use  binary and run through command line tool with project path and all. 

Is there any setting we can do to avoid "iOS Distribution Certificate and profile error" while running command.
Currently, I see this error when I run Swiftshield command for project:
 note: Using new build system
note: Planning build
note: Constructing build description
error: No signing certificate "iOS Distribution" found: No "iOS Distribution" signing certificate matching team ID "XXXXXXX" with a private key was found. (in target 'TestProject' from project 'TestProject')

** BUILD FAILED **
Fatal error: It looks like xcodebuild failed which prevents SwiftShield from proceeding. The log was printed above.: file /Users/bruno.rocha/Desktop/PersonalCodes/swiftshield/swiftshield-Sources/XcodeProjectBuilder.swift, line 48
Illegal instruction: 4


Is it mandatory to have Certificate and Profile in project to run Swiftshield ?

**Comment by rockbruno** [comment]
I think there is a way, but I'm not aware of it right now. This started being necessary after a specific xcode update. Any reason why your project doesn't have the profiles setup?

**Comment by amolpict** [comment]
Due to some client limitation we can not have Certificate installed here and test. 😟. Is there any way to test obfuscation . i mean to run it from Jenkins or any other way.
Please suggest if know about testing it without certificate , that would be helpful.
Due to certificate thing, blocked further to test actually.

**Comment by amolpict** [comment]
We can close the issue as this is working fine for me with Certificate and profile. @rockbruno  Thanks for help
